# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial (231cd615-b5c0-4fa9-889f-464c9c6325b4)'
    subscriptionId: '231cd615-b5c0-4fa9-889f-464c9c6325b4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'R1'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'iam6639/redis_caching_nodejs/aks-ix-digitalthread'
    deploymentMode: 'Incremental'